// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwsvGxKNHxa9X1qJ_-xAEJsDX0EYzN1rs',
    appId: '1:823177098138:web:a756b8d1ff7883d6f6c023',
    messagingSenderId: '823177098138',
    projectId: 'ledgu-c8222',
    authDomain: 'ledgu-c8222.firebaseapp.com',
    storageBucket: 'ledgu-c8222.firebasestorage.app',
    measurementId: 'G-ZHMD0JGSX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpziYvEGL2B9lYcwG8eWpMcXzUPytELwo',
    appId: '1:823177098138:android:a4908916586c139ef6c023',
    messagingSenderId: '823177098138',
    projectId: 'ledgu-c8222',
    storageBucket: 'ledgu-c8222.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD63bBm8mE2O6PGVMIJ7wAU-AGW2WAUEwc',
    appId: '1:823177098138:ios:b31ecc4a87e40c7ef6c023',
    messagingSenderId: '823177098138',
    projectId: 'ledgu-c8222',
    storageBucket: 'ledgu-c8222.firebasestorage.app',
    iosBundleId: 'com.example.ledgu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwsvGxKNHxa9X1qJ_-xAEJsDX0EYzN1rs',
    appId: '1:823177098138:web:4cc2347f7a3c8761f6c023',
    messagingSenderId: '823177098138',
    projectId: 'ledgu-c8222',
    authDomain: 'ledgu-c8222.firebaseapp.com',
    storageBucket: 'ledgu-c8222.firebasestorage.app',
    measurementId: 'G-MR5Y376EWK',
  );
}
